# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Deshotel Development
email: admin@deshoteldevelopment.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome! This test site is meant to serve as a blog and a portfolio of sorts as 
  I dive into the exciting world of web development. Please check back often to follow my
  progress and learn with me.
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "http://www.deshoteldevelopment.com" # the base hostname & protocol for your site
twitter_username: coming-soon
github_username:  Deshotel Development

# Build settings
markdown: kramdown
